### ISSUE TITLE
Remove guest users registers from DynamoDB when disconnect

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-lambda-websocket#25]
### Description

When a guest user leave from the application, the system must to remove his/her record on DynamoDB. A solution is create a websocket that handle $disconnect event and remove it from database afterwards.

### Tasks

- [ ] Create a websocket for $disconnect even
- [ ] Delete user by connection id
- [ ] Validate if the user is a guest
