### ISSUE TITLE
Block users from a chatroom

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-lambda-websocket#26]
### Description
As a owner of a chat room, need to block or ban user in real time.  The system should be send a real time notification the reason why he/she is banned

### Tasks

- [ ] Enable an endpoint for blocking a user from a chat room
- [ ] Add a new field on chat room database that stores all blocked users.
- [ ] Validate that owner can block users from their chat room
- [ ] Add a websocket that notify directly to the user banned
