### ISSUE TITLE
Create room

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-lambda-websocket#5]
### Description

Authenticated user can be able to create chat rooms.

### Acceptance Criteria
- Add a title is required
- Add a black list of words (Option)

### Tasks

- [x] Title field should be required
- [x] Owner field **(required)**
- [x] Black List words **(option)** 
- [x] Connections Ids of users **(Empty array)**
- [x] Add dynamoDB Table configuration in serverless.yml file
- [x] Testing endpoint
- [x] Enable an endpoint for register chatrooms

### Technical specs

DynamoDB Table (chatroom)
- id (unique id)
- owner_id (User id of owner)
- title (string)
- black_list_words (Array of string)
- connections_ids (Array of unique ids)

### Discoveries

- In DynamoDB when using the method `putItem(args)` it response the field `Atrributes` undefined because the params `ReturnValues` are not defined.  I tried to put the value `ALL_NEW` or `ALL_OLD` but still response the `Attributes: undefined`.
 
  Ref: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#API_PutItem_RequestParameters
  
  
  Solution:
  Working with the function `updateItem(args)` and set the param `ReturnValues: 'ALL_NEW'` works.
  
  Ref: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#API_UpdateItem_RequestParameters

- Marshall and unmarshall from [@aws-sdk/util-dynamodb](https://www.npmjs.com/package/@aws-sdk/util-dynamodb) library parse request and response items.
