### ISSUE TITLE
Send Messages

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-lambda-websocket#6]
### Description
Guest or Authenticated can be able to send message in chat rooms

### Acceptance Criteria
- Message should not be empty

### Tasks
- [x] Enable Websockets that sends this message to the others member in the chat.
- [x] Store the message in a DynamoDB table
- [x] Validate the message have more than 0 characters

### Technical Specs
DynamoDB Table (messages_chatroom)

- id (unique id)
- chatroom_id (Chatroom id)
- message (string)
- sender_id (id of the user that sent the message)
